dist: focal
language: bash
services: docker

env:
  - VERSION=jdk8
  - VERSION=jre8
  - VERSION=jdk11
  - VERSION=jre11
  - VERSION=jdk15
  - VERSION=jre15

before_install:
  - env | sort
  - cd "${VERSION}"
  - image="groovy:${VERSION}"
  - docker images --format "table {{.Repository}}:{{.Tag}}" | tail --lines=+2 | grep "adoptopenjdk" | xargs --no-run-if-empty docker pull
  - wget --quiet --output-document=- https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh | bash

install:
  - docker build --tag "${image}" .

script:
  - cd ../test
  - ./run.sh "${image}" "3.0.6"
